### ISSUE TITLE
install fails with sql error

### ISSUE THREAD

**Issue by kaly-x** [infinity-next/infinity-next#221]
when I run php artisan db:seed I receive the following error..

````

Seeding admin user.
User "Admin" has been created with the following password:
zdfsgdfgdfhdfhfgjhsdgfbfgdg
Seeded: UserSeeder
Seeding boards.
Success. At least one board exists now. Accessible at /test/.
Seeded: BoardSeeder
Seeding roles.
	Prepping database.
	Inserting system roles.
	Cleaning up relationships.
	Inserting board owner roles.
	/test/ has no owner role.
Seeded: RoleSeeder
Seeding role to user associations.
Seeded: UserRoleSeeder
Seeding permissions.
Done. Seeded 52 new permission(s).
Seeded: PermissionSeeder
Seeding permission groups and relationships.
Seeded: PermissionGroupSeeder
Seeding permission to role associations.
Seeded: RolePermissionSeeder
Seeding system options.
Done. Seeded 56 new permission(s).
Seeded: OptionSeeder
Seeding option groups and relationships.
[2015-12-31 22:07:18] local.ERROR: exception 'PDOException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`soykaf`.`option_group_assignments`, CONSTRAINT `option_group_assignments_option_name_foreign` FOREIGN KEY (`option_name`) REFERENCES `options` (`option_name`) ON DELETE CASCADE ON UPDATE CASC)' in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:390
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(390): PDOStatement->execute(Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(644): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'insert into `op...', Array)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(611): Illuminate\Database\Connection->runQueryCallback('insert into `op...', Array, Object(Closure))
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(391): Illuminate\Database\Connection->run('insert into `op...', Array, Object(Closure))
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(347): Illuminate\Database\Connection->statement('insert into `op...', Array)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1785): Illuminate\Database\Connection->insert('insert into `op...', Array)
#6 [internal function]: Illuminate\Database\Query\Builder->insert(Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(947): call_user_func_array(Array, Array)
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1630): Illuminate\Database\Eloquent\Builder->__call('insert', Array)
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1630): Illuminate\Database\Eloquent\Builder->insert(Array)
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1514): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#11 /var/www/html/database/seeds/OptionSeeder.php(547): Illuminate\Database\Eloquent\Model->save()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(42): OptionGroupSeeder->run()
#13 /var/www/html/database/seeds/DatabaseSeeder.php(38): Illuminate\Database\Seeder->call('OptionGroupSeed...')
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(61): DatabaseSeeder->run()
#15 [internal function]: Illuminate\Database\Console\Seeds\SeedCommand->fire()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#18 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/vendor/symfony/console/Application.php(837): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Seeds\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 /var/www/html/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 {main}

Next exception 'Illuminate\Database\QueryException' with message 'SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`soykaf`.`option_group_assignments`, CONSTRAINT `option_group_assignments_option_name_foreign` FOREIGN KEY (`option_name`) REFERENCES `options` (`option_name`) ON DELETE CASCADE ON UPDATE CASC) (SQL: insert into `option_group_assignments` (`option_name`, `option_group_id`, `display_order`) values (captchaEnabled, 11, 0))' in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:651
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(611): Illuminate\Database\Connection->runQueryCallback('insert into `op...', Array, Object(Closure))
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(391): Illuminate\Database\Connection->run('insert into `op...', Array, Object(Closure))
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(347): Illuminate\Database\Connection->statement('insert into `op...', Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1785): Illuminate\Database\Connection->insert('insert into `op...', Array)
#4 [internal function]: Illuminate\Database\Query\Builder->insert(Array)
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(947): call_user_func_array(Array, Array)
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1630): Illuminate\Database\Eloquent\Builder->__call('insert', Array)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1630): Illuminate\Database\Eloquent\Builder->insert(Array)
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1514): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder), Array)
#9 /var/www/html/database/seeds/OptionSeeder.php(547): Illuminate\Database\Eloquent\Model->save()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Seeder.php(42): OptionGroupSeeder->run()
#11 /var/www/html/database/seeds/DatabaseSeeder.php(38): Illuminate\Database\Seeder->call('OptionGroupSeed...')
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Console/Seeds/SeedCommand.php(61): DatabaseSeeder->run()
#13 [internal function]: Illuminate\Database\Console\Seeds\SeedCommand->fire()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(150): Illuminate\Container\Container->call(Array)
#16 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#18 /var/www/html/vendor/symfony/console/Application.php(837): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#19 /var/www/html/vendor/symfony/console/Application.php(189): Symfony\Component\Console\Application->doRunCommand(Object(Illuminate\Database\Console\Seeds\SeedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#20 /var/www/html/vendor/symfony/console/Application.php(120): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(107): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 /var/www/html/artisan(36): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 {main}



  [Illuminate\Database\QueryException]
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a ch
  ild row: a foreign key constraint fails (`soykaf`.`option_group_assignments`, C
  ONSTRAINT `option_group_assignments_option_name_foreign` FOREIGN KEY (`option_n
  ame`) REFERENCES `options` (`option_name`) ON DELETE CASCADE ON UPDATE CASC) (S
  QL: insert into `option_group_assignments` (`option_name`, `option_group_id`, `
  display_order`) values (captchaEnabled, 11, 0))



  [PDOException]
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a ch
  ild row: a foreign key constraint fails (`soykaf`.`option_group_assignments`, C
  ONSTRAINT `option_group_assignments_option_name_foreign` FOREIGN KEY (`option_n
  ame`) REFERENCES `options` (`option_name`) ON DELETE CASCADE ON UPDATE CASC)

````

**Comment by kaly-x** [comment]
Is it wise to set SET FOREIGN_KEY_CHECKS=0 ?

**Comment by jaw-sh** [comment]
No. Please allow me to fix this later; I'm busy with 8chan's migration. 
Setting up new instances of Next hasn't taken priority in some time.

**Comment by jaw-sh** [comment]
This looks like a trivial fix. The seeder is always complaining about 
weird shit. In this instance, it looks like it's trying to assign an 
option that doesn't exist to a group. I need to pluck an item from an 
array somewhere.

**Comment by kaly-x** [comment]
I added this after line 160 in database/seeds/OptionSeeder.php and it continued without an error, lets see what happens next.

```				
[
					'option_name'           => "captchaEnabled",
					'default_value'         => 0,
					'format'                => "onoff",
					'data_type'             => "boolean",
					'validation_parameters' => 'boolean'
],
````

**Comment by b3y0ndd34th** [comment]
Thanks for the update kaly-x

That definitely got past the hang up for the "php artisan db:seed" command.

Unfortunately, after the command completed and displayed my password, the boards do not work.  Is there something more we have to do to get the boards to display?

Was your installation successful and was your board working after making this change kaly-x?

**Comment by kaly-x** [comment]
No not at all everything was super broken and unusable after I was able to finish the installation.

**Comment by b3y0ndd34th** [comment]
LOL

Okay, no problem, as long as I am not alone!

**Comment by b3y0ndd34th** [comment]
Apparently we need to wait for another version...

https://github.com/infinity-next/infinity-next/issues/188

Jawsh said the installation instructions are for version 0.5.0

That's unfortunate :(

**Comment by jaw-sh** [comment]
Yeah, very sorry -- I'd make this priority #1 but there's some fires to 
put out. I promise I haven't forgotten.

**Comment by b3y0ndd34th** [comment]
We see you making commits we know you're working ;)
We aren't asking for an eta or gathering any pitchforks :p 

If I figure anything else out to get a working installation, I promise to document as best I can, and share.

Until then we will be waiting and rooting for you.

**Comment by b3y0ndd34th** [comment]
Thanks for fixing this!

I got my installation working ;)
