### ISSUE TITLE
Friend cannot login with his login details, but I can

### ISSUE THREAD

**Issue by weja** [infinity-next/infinity-next#264]
Login doesn't work for certain user.. I tried logging in with his details, and for me it works.
But he is unable to login.. He tried several different browsers (shouldn't matter really, I guess)..

Nginx error:

[error] 1277#0: *2060 FastCGI sent in stderr: "PHP message: [2016-02-18 14:52:48] local.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' with message 'No query results for model [App\User].' in /path/to/inf/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:157
Stack trace:
#0 /path/to/inf/app/Http/Controllers/Panel/AuthController.php(123): Illuminate\Database\Eloquent\Builder->firstOrFail()
#1 [internal function]: App\Http\Controllers\Panel\AuthController->postLogin(Object(Illuminate\Http\Request))
#2 /path/to/inf/bootstrap/cache/compiled.php(8873): call_user_func_array(Array, Array)
#3 /path/to/inf/bootstrap/cache/compiled.php(8942): Illuminate\Routing\Controller->callAction('postLogin', Array)
#4 /path/to/inf/bootstrap/cache/compiled.php(8922): Illuminate\Routing\ControllerDispatcher->call(Object(App\Http\Controllers\Panel\AuthController), Object(Illuminate\Routing\Route), 'postLogin')
#5 [internal function]: Illuminate\Routing\Contro" while reading response header from upstream, client: ***, server: 8pallo.fi, request: "POST /cp/auth/login HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "8pallo.fi", referrer: "https://8pallo.fi/cp/auth/login"

**Comment by jaw-sh** [comment]
Usernames are case sensitive. I will patch this today.
